#!/usr/bin/python3
import sys
import psycopg2
from helpers import subjectExists, termExists, getSubjectName

if len(sys.argv) < 3:
   print(f"Usage: {sys.argv[0]} subject term")
   exit(1)

subject = sys.argv[1]
term = sys.argv[2]

conn = None
try:
   conn = psycopg2.connect("dbname=mymyunsw")
   cur = conn.cursor()

   if not subjectExists(conn, subject):
      print(f"Invalid subject {subject}")
      exit(1)
      
   if not termExists(conn, term):
      print(f"Invalid term {term}")
      exit(1)

   subjName = getSubjectName(conn, subject, term)
   if subjName is None:
      print(f"No offering: {subject} {term}")
      exit(1)

   query = "select * from student_info(%s, %s)"
   cur.execute(query, [subject, term])

   name, = subjName
   print(f"{subject} {term} {name}")

   students = cur.fetchall()
   if len(students) == 0:
      print("No students")
      exit(0)

   for student in students:
      id, family, given = student
      print(f"{id} {family}, {given}")

except psycopg2.Error as err:
   print("database error: ", err)
finally:
   if conn :
      conn.close()
