#!/usr/bin/python3
import sys
import psycopg2

if len(sys.argv) < 3:
   print(f"Usage: {sys.argv[0]} subject term")
   exit(1)

subject = sys.argv[1]
term = sys.argv[2]

conn = None
try:
   conn = psycopg2.connect("dbname=mymyunsw")
   cur = conn.cursor()

   # query = "select id, family, given from student_info where subj = %s and term = %s"
   query = "select * from student_info(%s, %s)"
   cur.execute(query, [subject, term])

   print(f"{subject} {term}")
   students = cur.fetchall()
   if len(students) == 0:
      print("No students")
      exit(0)

   for student in students:
      id, family, given = student
      print(f"{id} {family}, {given}")

except psycopg2.Error as err:
   print("database error: ", err)
finally:
   if conn :
      conn.close()
