#!/usr/bin/python3
import sys
import psycopg2
from helpers import subjectExists, termExists, getCourseName

if len(sys.argv) < 3:
   print(f"Usage: {sys.argv[0]} subject term")
   exit(1)

subject = sys.argv[1]
term = sys.argv[2]

conn = None
try:
   conn = psycopg2.connect("dbname=mymyunsw")
   cur = conn.cursor()

   query = "select * from student_info(%s, %s)"
   cur.execute(query, [subject, term])

   if not subjectExists(conn, subject):
      print(f"Invalid subject {subject}")
      exit(1)

   if not termExists(conn, term):
      print(f"Invalid term {term}")
      exit(1)

   course = getCourseName(conn, subject, term)
   if course is None:
      print(f"No offering {subject} {term}")
      exit(1)
   
   courseName, = course
   print(f"{subject} {term} {courseName}")

   students = cur.fetchall()
   if len(students) == 0:
      print("No students")
      exit(0)

   for student in students:
      id, family, given = student
      print(f"{id} {family}, {given}")

except psycopg2.Error as err:
   print("database error: ", err)
finally:
   if conn :
      conn.close()
